---
title: About me
date: ""
comments: false
---


__Work:__ I currently work as a Senior Analyst in the healthcare industry. Prior to that, I was a Senior Data Analyst in the non-profit/fundraising sector. I got my start in data through working in analytics and reporting for a private financing company. On the side, I've been a volunteer data scientist for a few different organizations.

__Education:__ I graduated with an MS in Statistics from the [University of Wisconsin](https://www.wisc.edu/) in 2017 (go Badgers! `r emo::ji("open_hands")`). Prior to that, I graduated with a BS in Mathematical Statistics and Mathematical Economics from [St. Cloud State University](https://www.stcloudstate.edu/) in 2015 (go Huskies! `r emo::ji("wolf")`). 

__Personal:__ I live in [Madison, WI](http://www.cityofmadison.com/). I like to spend my spare time reading, playing guitar, playing golf, biking, and watching whatever Wisconsin sports team is on television. 

My email is bgstieber (at) gmail (dot) com